export const data = [
    {
        id: 1,
        name: 'San Sebastián',
        location: 'La Plata',
        date: '20 de enero',
        description: 'El Festival Folclórico, Reinado Nacional del Bambuco y Muestra Internacional del Folclor, es una de las fiestas más importantes del sur de Colombia, específicamente del departamento del Huila, cuya capital, Neiva, es la sede del festival. Se realizan en honor a San Juan y San Pedro.',
        img: require('../../assets/img/imagen1.jpg'),
    },
    {
        id: 2,
        name: 'Nuestra Señora de Lourdes',
        location: 'Algeciras',
        date: '20 de enero',
        description: 'El Festival Folclórico, Reinado Nacional del Bambuco y Muestra Internacional del Folclor, es una de las fiestas más importantes del sur de Colombia, específicamente del departamento del Huila, cuya capital, Neiva, es la sede del festival. Se realizan en honor a San Juan y San Pedro.',
        img: require('../../assets/img/imagen2.jpg'),
    },
    {
        id: 3,
        name: 'San Sebastián',
        location: 'San Agustin',
        date: '20 de enero',
        description: 'El Festival Folclórico, Reinado Nacional del Bambuco y Muestra Internacional del Folclor, es una de las fiestas más importantes del sur de Colombia, específicamente del departamento del Huila, cuya capital, Neiva, es la sede del festival. Se realizan en honor a San Juan y San Pedro.',
        img: require('../../assets/img/imagen3.jpg'),
    },
    {
        id: 4,
        name: 'San Sebastián',
        location: 'La Plata',
        date: '20 de enero',
        description: 'El Festival Folclórico, Reinado Nacional del Bambuco y Muestra Internacional del Folclor, es una de las fiestas más importantes del sur de Colombia, específicamente del departamento del Huila, cuya capital, Neiva, es la sede del festival. Se realizan en honor a San Juan y San Pedro.',
        img: require('../../assets/img/imagen4.jpg'),
    },
    {
        id: 5,
        name: 'San Sebastián',
        location: 'La Plata',
        date: '20 de enero',
        description: 'El Festival Folclórico, Reinado Nacional del Bambuco y Muestra Internacional del Folclor, es una de las fiestas más importantes del sur de Colombia, específicamente del departamento del Huila, cuya capital, Neiva, es la sede del festival. Se realizan en honor a San Juan y San Pedro.',
        img: require('../../assets/img/imagen1.jpg'),
    },
    {
        id: 6,
        name: 'San Sebastián',
        location: 'La Plata',
        date: '20 de enero',
        description: 'El Festival Folclórico, Reinado Nacional del Bambuco y Muestra Internacional del Folclor, es una de las fiestas más importantes del sur de Colombia, específicamente del departamento del Huila, cuya capital, Neiva, es la sede del festival. Se realizan en honor a San Juan y San Pedro.',
        img: require('../../assets/img/imagen2.jpg'),
    },
]

